2021-05-15 18:17:47,896 - __main__ - INFO - Starting Bot !
2021-05-15 18:28:53,998 - __main__ - INFO - Starting Bot !
2021-05-15 18:32:43,178 - __main__ - INFO - Starting Bot !
2021-05-15 18:35:56,121 - __main__ - INFO - Starting Bot !
2021-05-15 18:36:13,264 - __main__ - INFO - Starting Bot !
2021-05-15 18:37:02,373 - __main__ - INFO - Starting Bot !
2021-05-15 18:40:12,681 - __main__ - INFO - Starting Bot !
2021-05-15 18:40:54,500 - __main__ - INFO - Starting Bot !
2021-05-15 18:41:26,336 - __main__ - INFO - Starting Bot !
2021-05-15 18:45:00,951 - __main__ - INFO - Starting Bot !
2021-05-15 18:45:23,823 - __main__ - INFO - Starting Bot !
2021-05-15 18:45:27,937 - root - INFO - Started 8 HandlerTasks
2021-05-15 18:46:29,166 - bot - INFO - AuthURL:570339985
2021-05-15 18:47:33,924 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 18:47:34,282 - root - INFO - Stopped 8 HandlerTasks
2021-05-15 18:47:34,283 - __main__ - INFO - Bot Stopped !
2021-05-15 18:47:44,201 - __main__ - INFO - Starting Bot !
2021-05-15 18:47:49,062 - root - INFO - Started 8 HandlerTasks
2021-05-15 18:48:12,281 - bot - INFO - AuthURL:570339985
2021-05-15 18:54:14,412 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 18:54:15,198 - root - INFO - Stopped 8 HandlerTasks
2021-05-15 18:54:15,200 - __main__ - INFO - Bot Stopped !
2021-05-15 18:54:18,437 - __main__ - INFO - Starting Bot !
2021-05-15 18:54:22,171 - root - INFO - Started 8 HandlerTasks
2021-05-15 18:54:28,298 - bot - INFO - AuthURL:570339985
2021-05-15 18:59:04,282 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 18:59:05,012 - root - INFO - Stopped 8 HandlerTasks
2021-05-15 18:59:05,015 - __main__ - INFO - Bot Stopped !
2021-05-15 18:59:09,220 - __main__ - INFO - Starting Bot !
2021-05-15 18:59:12,617 - root - INFO - Started 8 HandlerTasks
2021-05-15 19:00:12,381 - bot - INFO - AuthURL:869313859
2021-05-15 19:04:52,283 - bot - INFO - AuthURL:944732052
2021-05-15 19:12:37,451 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 19:12:37,834 - root - INFO - Stopped 8 HandlerTasks
2021-05-15 19:12:37,837 - __main__ - INFO - Bot Stopped !
2021-05-15 19:12:40,944 - __main__ - INFO - Starting Bot !
2021-05-15 19:12:44,789 - root - INFO - Started 8 HandlerTasks
2021-05-15 19:12:54,461 - bot - INFO - AuthURL:570339985
2021-05-15 19:16:37,791 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 19:16:38,389 - root - INFO - Stopped 8 HandlerTasks
2021-05-15 19:16:38,391 - __main__ - INFO - Bot Stopped !
2021-05-15 19:16:41,748 - __main__ - INFO - Starting Bot !
2021-05-15 19:16:47,404 - root - INFO - Started 8 HandlerTasks
2021-05-15 19:17:08,315 - bot - INFO - AuthURL:570339985
2021-05-15 19:17:47,880 - bot - INFO - AuthURL:944732052
2021-05-15 19:20:02,544 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 19:20:02,967 - root - INFO - Stopped 8 HandlerTasks
2021-05-15 19:20:02,970 - __main__ - INFO - Bot Stopped !
2021-05-15 19:20:07,015 - __main__ - INFO - Starting Bot !
2021-05-15 19:20:11,747 - root - INFO - Started 8 HandlerTasks
2021-05-15 19:20:33,278 - bot - INFO - AuthURL:570339985
2021-05-15 19:31:46,559 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 19:31:46,695 - root - INFO - Stopped 8 HandlerTasks
2021-05-15 19:31:46,698 - __main__ - INFO - Bot Stopped !
2021-05-15 19:31:49,734 - __main__ - INFO - Starting Bot !
2021-05-15 19:31:56,356 - root - INFO - Started 8 HandlerTasks
2021-05-15 19:31:58,853 - bot - INFO - AuthURL:570339985
2021-05-15 19:34:52,172 - bot - INFO - AuthURL:570339985
2021-05-15 19:41:26,224 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 19:41:26,906 - root - INFO - Stopped 8 HandlerTasks
2021-05-15 19:41:26,909 - __main__ - INFO - Bot Stopped !
2021-05-15 19:41:31,632 - __main__ - INFO - Starting Bot !
2021-05-15 19:41:35,176 - root - INFO - Started 8 HandlerTasks
2021-05-15 19:41:46,549 - bot - INFO - AuthURL:570339985
2021-05-15 19:53:06,894 - bot - INFO - AuthURL:570339985
2021-05-15 19:58:12,468 - bot - INFO - AuthURL:570339985
2021-05-15 20:01:18,718 - bot - INFO - AuthURL:570339985
2021-05-15 20:04:24,720 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:04:24,863 - root - INFO - Stopped 8 HandlerTasks
2021-05-15 20:04:24,865 - __main__ - INFO - Bot Stopped !
2021-05-15 20:04:28,929 - __main__ - INFO - Starting Bot !
2021-05-15 20:04:32,948 - root - INFO - Started 8 HandlerTasks
2021-05-15 20:04:44,228 - bot - INFO - AuthURL:570339985
2021-05-15 20:17:13,476 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:17:14,039 - root - INFO - Stopped 8 HandlerTasks
2021-05-15 20:17:14,043 - __main__ - INFO - Bot Stopped !
2021-05-15 20:17:17,479 - __main__ - INFO - Starting Bot !
2021-05-15 20:17:20,647 - root - INFO - Started 8 HandlerTasks
2021-05-15 20:17:30,236 - bot - INFO - AuthURL:570339985
2021-05-15 20:40:25,437 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:40:25,616 - root - INFO - Stopped 8 HandlerTasks
2021-05-15 20:40:25,619 - __main__ - INFO - Bot Stopped !
2021-05-15 20:40:28,657 - __main__ - INFO - Starting Bot !
2021-05-15 20:40:32,431 - root - INFO - Started 8 HandlerTasks
2021-05-15 20:41:44,557 - bot - INFO - AuthURL:570339985
2021-05-15 20:47:49,148 - bot - INFO - AuthSuccess: 570339985
2021-05-15 20:49:40,867 - bot - INFO - Download:570339985: BQADBQADNgEAAjCV2VXWciiGrUkMwRYE
2021-05-15 20:49:59,260 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:03,662 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:04,211 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:04,438 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:04,766 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:04,924 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:05,077 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:05,220 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:05,532 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:06,033 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:06,118 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:06,201 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:06,283 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:06,369 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:06,451 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:06,535 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:06,617 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:06,702 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:06,787 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:06,868 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:06,953 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:07,038 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:07,118 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:07,205 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:07,288 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:07,372 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:07,457 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:07,541 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:07,626 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:07,710 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:07,791 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:07,877 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:50:07,960 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 20:51:53,354 - __main__ - INFO - Starting Bot !
2021-05-15 20:51:58,374 - root - INFO - Started 8 HandlerTasks
2021-05-15 20:52:24,971 - bot - INFO - AuthURL:243537390
2021-05-15 20:52:58,316 - bot - INFO - AuthSuccess: 243537390
2021-05-15 20:53:33,325 - bot - INFO - Download:243537390: BQADBQADIQMAAkkmAAFV-qn2k-Ku3KAWBA
2021-05-15 20:53:35,838 - bot - INFO - Upload: /Users/ajaybabu/Desktop/Uchihas bot/bot/downloads/log.txt
2021-05-15 20:53:39,901 - bot - INFO - Deleteing: /Users/ajaybabu/Desktop/Uchihas bot/bot/downloads/log.txt
2021-05-15 20:56:15,956 - bot - INFO - Download:243537390: AgADBQADdqwxG0kmAAFV7Bhrr6f0oJSZg0xzdAADAQADAgADdwAD774BAAEWBA
2021-05-15 20:56:20,074 - bot - INFO - Upload: /Users/ajaybabu/Desktop/Uchihas bot/bot/downloads/IMG-243537390-63.png
2021-05-15 20:56:24,920 - bot - INFO - Deleteing: /Users/ajaybabu/Desktop/Uchihas bot/bot/downloads/IMG-243537390-63.png
2021-05-15 21:05:25,244 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:05:25,470 - root - INFO - Stopped 8 HandlerTasks
2021-05-15 21:05:25,474 - __main__ - INFO - Bot Stopped !
2021-05-15 21:05:29,463 - __main__ - INFO - Starting Bot !
2021-05-15 21:05:35,423 - root - INFO - Started 8 HandlerTasks
2021-05-15 21:05:41,768 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:05:42,456 - root - INFO - Stopped 8 HandlerTasks
2021-05-15 21:05:42,457 - __main__ - INFO - Bot Stopped !
2021-05-15 21:05:44,444 - __main__ - INFO - Starting Bot !
2021-05-15 21:05:50,186 - root - INFO - Started 8 HandlerTasks
2021-05-15 21:07:34,659 - bot - INFO - YTDL:570339985: https://youtu.be/VBqlfeTP708
2021-05-15 21:07:39,368 - bot - WARNING - You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
2021-05-15 21:08:15,305 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:17,241 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:17,740 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:17,824 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:17,908 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:17,992 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:18,077 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:18,160 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:18,245 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:18,326 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:18,411 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:18,494 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:18,578 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:18,662 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:18,747 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:18,832 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:18,915 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:19,001 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:19,084 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:19,166 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:19,251 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:19,334 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:19,419 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:19,504 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:19,586 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:19,671 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:19,754 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:19,839 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:19,922 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:20,005 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:20,089 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:20,174 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:20,258 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:20,341 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:20,423 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:20,507 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:20,592 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:20,676 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:20,758 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:20,842 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:20,926 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:21,010 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:08:21,094 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:09:49,829 - __main__ - INFO - Starting Bot !
2021-05-15 21:09:54,020 - root - INFO - Started 8 HandlerTasks
2021-05-15 21:10:01,879 - bot - INFO - Download:570339985: https://youtu.be/QC8iQqtG0hg
2021-05-15 21:10:05,429 - bot - INFO - Downloading: https://youtu.be/QC8iQqtG0hg in ./downloads/
2021-05-15 21:10:10,073 - bot - INFO - Upload: ./downloads/QC8iQqtG0hg
2021-05-15 21:10:15,443 - bot - INFO - Deleteing: ./downloads/QC8iQqtG0hg
2021-05-15 21:11:43,953 - bot - INFO - YTDL:570339985: https://youtu.be/QC8iQqtG0hg
2021-05-15 21:11:47,154 - bot - WARNING - You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
2021-05-15 21:14:08,266 - bot - INFO - YTDL:570339985: https://youtu.be/QC8iQqtG0hg
2021-05-15 21:14:11,167 - bot - WARNING - You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
2021-05-15 21:14:34,170 - pyrogram.syncer - CRITICAL - attempt to write a readonly database
Traceback (most recent call last):
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/syncer.py", line 72, in worker
    await asyncio.wait_for(cls.event.wait(), cls.INTERVAL)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/syncer.py", line 84, in sync
    await client.storage.save()
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 81, in save
    await self.date(int(time.time()))
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 166, in date
    return self._accessor(value)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 154, in _accessor
    return self._get() if value == object else self._set(value)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 148, in _set
    self.conn.execute(
sqlite3.OperationalError: attempt to write a readonly database
2021-05-15 21:14:48,642 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-411' coro=<Client.handle_updates() done, defined at /Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/client.py:523> exception=OperationalError('attempt to write a readonly database')>
Traceback (most recent call last):
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/client.py", line 525, in handle_updates
    is_min = (await self.fetch_peers(updates.users)) or (await self.fetch_peers(updates.chats))
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/client.py", line 480, in fetch_peers
    await self.storage.update_peers(parsed_peers)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 95, in update_peers
    self.conn.executemany(
sqlite3.OperationalError: attempt to write a readonly database
2021-05-15 21:14:54,179 - pyrogram.syncer - CRITICAL - attempt to write a readonly database
Traceback (most recent call last):
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/syncer.py", line 72, in worker
    await asyncio.wait_for(cls.event.wait(), cls.INTERVAL)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/syncer.py", line 84, in sync
    await client.storage.save()
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 81, in save
    await self.date(int(time.time()))
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 166, in date
    return self._accessor(value)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 154, in _accessor
    return self._get() if value == object else self._set(value)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 148, in _set
    self.conn.execute(
sqlite3.OperationalError: attempt to write a readonly database
2021-05-15 21:15:14,187 - pyrogram.syncer - CRITICAL - attempt to write a readonly database
Traceback (most recent call last):
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/syncer.py", line 72, in worker
    await asyncio.wait_for(cls.event.wait(), cls.INTERVAL)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/syncer.py", line 84, in sync
    await client.storage.save()
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 81, in save
    await self.date(int(time.time()))
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 166, in date
    return self._accessor(value)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 154, in _accessor
    return self._get() if value == object else self._set(value)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 148, in _set
    self.conn.execute(
sqlite3.OperationalError: attempt to write a readonly database
2021-05-15 21:15:35,338 - bot - INFO - YTDL:570339985: https://youtu.be/QC8iQqtG0hg
2021-05-15 21:15:38,369 - bot - WARNING - You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
2021-05-15 21:16:32,434 - root - INFO - Stop signal received (2). Exiting...
2021-05-15 21:16:33,112 - root - INFO - Stopped 8 HandlerTasks
2021-05-15 21:16:33,114 - __main__ - INFO - Bot Stopped !
2021-05-16 10:06:23,195 - __main__ - INFO - Starting Bot !
2021-05-16 10:06:27,109 - root - INFO - Started 8 HandlerTasks
2021-05-16 10:10:28,142 - pyrogram.dispatcher - ERROR - [400 MESSAGE_NOT_MODIFIED]: The message was not modified because you tried to edit it using the same content (caused by "raw.functions.messages.EditMessage")
Traceback (most recent call last):
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 442, in send
    return await self._send(data, timeout=timeout)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 407, in _send
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 210, in handler_worker
    await self.loop.run_in_executor(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/plugins/help.py", line 30, in help_answer
    c.edit_message_text(chat_id = chat_id,    message_id = message_id,
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/sync.py", line 45, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, loop).result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/methods/messages/edit_message_text.py", line 78, in edit_message_text
    r = await self.send(
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/methods/advanced/send.py", line 68, in send
    r = await self.session.send(data, retries, timeout, self.sleep_threshold)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 461, in send
    return await self.send(data, retries - 1, timeout)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 442, in send
    return await self._send(data, timeout=timeout)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 412, in _send
    RPCError.raise_it(result, type(data))
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageNotModified: [400 MESSAGE_NOT_MODIFIED]: The message was not modified because you tried to edit it using the same content (caused by "raw.functions.messages.EditMessage")
2021-05-16 10:10:28,158 - pyrogram.dispatcher - ERROR - [400 MESSAGE_NOT_MODIFIED]: The message was not modified because you tried to edit it using the same content (caused by "raw.functions.messages.EditMessage")
Traceback (most recent call last):
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 442, in send
    return await self._send(data, timeout=timeout)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 407, in _send
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 210, in handler_worker
    await self.loop.run_in_executor(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/plugins/help.py", line 30, in help_answer
    c.edit_message_text(chat_id = chat_id,    message_id = message_id,
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/sync.py", line 45, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, loop).result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/methods/messages/edit_message_text.py", line 78, in edit_message_text
    r = await self.send(
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/methods/advanced/send.py", line 68, in send
    r = await self.session.send(data, retries, timeout, self.sleep_threshold)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 461, in send
    return await self.send(data, retries - 1, timeout)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 442, in send
    return await self._send(data, timeout=timeout)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 412, in _send
    RPCError.raise_it(result, type(data))
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageNotModified: [400 MESSAGE_NOT_MODIFIED]: The message was not modified because you tried to edit it using the same content (caused by "raw.functions.messages.EditMessage")
2021-05-16 10:10:28,390 - pyrogram.dispatcher - ERROR - [400 MESSAGE_NOT_MODIFIED]: The message was not modified because you tried to edit it using the same content (caused by "raw.functions.messages.EditMessage")
Traceback (most recent call last):
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 210, in handler_worker
    await self.loop.run_in_executor(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/plugins/help.py", line 30, in help_answer
    c.edit_message_text(chat_id = chat_id,    message_id = message_id,
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/sync.py", line 45, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, loop).result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/methods/messages/edit_message_text.py", line 78, in edit_message_text
    r = await self.send(
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/methods/advanced/send.py", line 68, in send
    r = await self.session.send(data, retries, timeout, self.sleep_threshold)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 442, in send
    return await self._send(data, timeout=timeout)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 412, in _send
    RPCError.raise_it(result, type(data))
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageNotModified: [400 MESSAGE_NOT_MODIFIED]: The message was not modified because you tried to edit it using the same content (caused by "raw.functions.messages.EditMessage")
2021-05-16 10:10:28,563 - pyrogram.dispatcher - ERROR - [400 MESSAGE_NOT_MODIFIED]: The message was not modified because you tried to edit it using the same content (caused by "raw.functions.messages.EditMessage")
Traceback (most recent call last):
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 210, in handler_worker
    await self.loop.run_in_executor(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/plugins/help.py", line 30, in help_answer
    c.edit_message_text(chat_id = chat_id,    message_id = message_id,
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/sync.py", line 45, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, loop).result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/methods/messages/edit_message_text.py", line 78, in edit_message_text
    r = await self.send(
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/methods/advanced/send.py", line 68, in send
    r = await self.session.send(data, retries, timeout, self.sleep_threshold)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 442, in send
    return await self._send(data, timeout=timeout)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 412, in _send
    RPCError.raise_it(result, type(data))
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageNotModified: [400 MESSAGE_NOT_MODIFIED]: The message was not modified because you tried to edit it using the same content (caused by "raw.functions.messages.EditMessage")
2021-05-16 10:11:08,935 - pyrogram.dispatcher - ERROR - [400 BUTTON_URL_INVALID]: The button url is invalid (caused by "raw.functions.messages.EditMessage")
Traceback (most recent call last):
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 210, in handler_worker
    await self.loop.run_in_executor(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/plugins/help.py", line 30, in help_answer
    c.edit_message_text(chat_id = chat_id,    message_id = message_id,
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/sync.py", line 45, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, loop).result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/methods/messages/edit_message_text.py", line 78, in edit_message_text
    r = await self.send(
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/methods/advanced/send.py", line 68, in send
    r = await self.session.send(data, retries, timeout, self.sleep_threshold)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 442, in send
    return await self._send(data, timeout=timeout)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 412, in _send
    RPCError.raise_it(result, type(data))
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ButtonUrlInvalid: [400 BUTTON_URL_INVALID]: The button url is invalid (caused by "raw.functions.messages.EditMessage")
2021-05-16 10:11:20,851 - pyrogram.dispatcher - ERROR - [400 BUTTON_URL_INVALID]: The button url is invalid (caused by "raw.functions.messages.EditMessage")
Traceback (most recent call last):
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 210, in handler_worker
    await self.loop.run_in_executor(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/plugins/help.py", line 30, in help_answer
    c.edit_message_text(chat_id = chat_id,    message_id = message_id,
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/sync.py", line 45, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, loop).result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/methods/messages/edit_message_text.py", line 78, in edit_message_text
    r = await self.send(
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/methods/advanced/send.py", line 68, in send
    r = await self.session.send(data, retries, timeout, self.sleep_threshold)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 442, in send
    return await self._send(data, timeout=timeout)
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/session/session.py", line 412, in _send
    RPCError.raise_it(result, type(data))
  File "/Users/ajaybabu/Desktop/Uchihas bot/bot/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ButtonUrlInvalid: [400 BUTTON_URL_INVALID]: The button url is invalid (caused by "raw.functions.messages.EditMessage")
2021-05-16 10:12:19,995 - bot - INFO - SetParent:570339985: 10nuE6v9JY-vZFbxVG11Od7PALaPVXNwe
2021-05-16 10:12:34,802 - bot - INFO - Download:570339985: AgADBQADdqwxG0kmAAFV7Bhrr6f0oJSZg0xzdAADAQADAgADdwAD774BAAEWBA
2021-05-16 10:12:36,577 - bot - INFO - Upload: /Users/ajaybabu/Desktop/Uchihas bot/bot/downloads/IMG-570339985-91.png
2021-05-16 10:12:50,885 - bot - INFO - Deleteing: /Users/ajaybabu/Desktop/Uchihas bot/bot/downloads/IMG-570339985-91.png
2021-05-16 10:14:10,077 - bot - INFO - Copy:570339985: https://drive.google.com/file/d/1yBL0pTSWTG7knqdSr7fN6X2u8cH962I_/view?usp=drivesdk
2021-05-16 10:14:31,738 - pyrogram.connection.connection - WARNING - timed out
2021-05-16 10:14:41,746 - pyrogram.connection.connection - WARNING - timed out
2021-05-16 10:32:13,723 - root - INFO - Stop signal received (2). Exiting...
2021-05-16 10:32:14,555 - root - INFO - Stopped 8 HandlerTasks
2021-05-16 10:32:14,557 - __main__ - INFO - Bot Stopped !
2021-05-16 10:36:46,786 - __main__ - INFO - Starting Bot !
2021-05-16 10:36:51,126 - root - INFO - Started 8 HandlerTasks
